version: '3'
services:
    servantly:
        build: .
        image: servantly
        command: servantly
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - servantly
